// Generated by the protocol buffer compiler.  DO NOT EDIT! \0_o/
// source: TextSecure.proto

#pragma once
/*
Port of class RequestMessage from TextSecure-android
*/

// [ ] done
// TFS ID: 358

class TextSecureProtos
{
public:
  class SyncMessage
  {
  public:
    class Request
    {
    public:
      enum Type
      {
        CONTACTS,
        GROUPS,
      };
    private:
      Type type;
    public:
      Type GetType()
      {
        return this->type;
      }
    };
  };
};
