// Generated by the protocol buffer compiler.  DO NOT EDIT! \0_o/
// source: TextSecure.proto

#pragma once
/*
Port of class RequestMessage from TextSecure-android
*/

// [ ] done
// TFS ID: 358

class TextSecureProtos
{
public:
  class SyncMessage
  {
  public:
    class Request
    {
    public:
      enum Type
      {
        CONTACTS,
        GROUPS,
      };
    private:
      Type type;
    public:
      Type GetType()
      {
        return this->type;
      }
    };
  };
  class ContactDetails
  {
  public:
    class Avatar
    {
    public:
      class Builder
      {
      public:
        void SetContentType(unsigned char* contentType);
        void SetLength(int len);
      };
    public:
      static Builder* NewBuilder();
    };
    class Builder
    {
    public:
      void SetNumber(unsigned char* number);
      void SetName(unsigned char* name);
      void SetAvatar(Avatar::Builder* avatar);
      ContactDetails* Build();
    };
  public:
    static Builder* NewBuilder();
  public:
    char* ToByteArray();
  };
};
